# make_readme.py

TICK = "`" * 3

lines = [
    "# 🚗 IlCarro Test Automation Framework\n\n",
    "Robust, production-ready hybrid test automation framework for the \"IlCarro\" (Car Rental) web application.\n\n",
    "This project demonstrates a senior-level approach to QA automation, combining classic UI testing, API integration, and modern tools to ensure fast, stable, and secure test execution.\n\n",
    "## 🛠️ Tech Stack\n",
    "* **Language:** Python 3.12\n",
    "* **Frameworks:** Pytest, Selenium WebDriver, Playwright (Sync API)\n",
    "* **API Testing:** Requests\n",
    "* **Data Generation:** Faker\n",
    "* **Reporting:** Allure Report\n",
    "* **CI/CD:** GitHub Actions, GitHub Pages\n",
    "* **Notifications:** Telegram Bot API\n\n",
    "## 🚀 Key Architectural Features\n\n",
    "* **Hybrid Testing Approach:** Tests use API calls to set up preconditions (e.g., creating a car or user) and teardown data, drastically reducing UI test execution time and ensuring test isolation.\n",
    "* **Dual Framework Support:** Implemented primarily using **Selenium (Page Object Model)** with an integrated **Playwright** module to demonstrate modern tool capabilities (Strict Mode, Auto-waiting, Browser Contexts).\n",
    "* **Smart Browser Cascading:** The framework automatically detects the environment. It runs headless Google Chrome in CI/CD (GitHub Actions) for consistency, but gracefully falls back to Microsoft Edge for local execution if Chrome is unavailable.\n",
    "* **Dynamic Data Generation:** Uses dynamic querying to the backend API to fetch a valid list of cities for testing, avoiding hardcoded data and preventing false negatives due to data desynchronization.\n",
    "* **Security & Log Masking:** Sensitive data (passwords, tokens) are strictly masked (********) in all console outputs, test logs, and Allure reports.\n",
    "* **Data Integrity Auditing:** Includes isolated Gray-box tests (test_dictionaries.py) to strictly validate frontend autocomplete dictionaries against backend API responses, automatically detecting silent business bugs and mapping mismatches without breaking functional UI tests.\n",
    "* **Parallel Execution Ready:** Configured to run concurrently using `pytest-xdist` with strictly isolated test environments.\n",
    "* **Data-Driven Testing (DDT):** Extensively utilizes `@pytest.mark.parametrize` to execute complex positive and negative test scenarios (e.g., isolating frontend validation from backend API errors) from a single test function, ensuring high coverage while strictly adhering to the DRY principle.\n",
    "* **Modern Data Modeling:** Implements Python `@dataclass` for representing test entities (e.g., `User`, `Car`). This architectural choice ensures clean object instantiation, dynamic payload overriding via `**kwargs`, and highly readable automatic logging of generated test data.\n",
    "* **Advanced Custom Logging:** Features a proprietary logging utility with dual-stream outputs. It provides real-time, ANSI-colored console logs for rapid local debugging and simultaneously writes clean, thread-safe logs to individual files, ensuring stable log capture during parallel execution (`pytest-xdist`).\n",
    "* **Executive-Ready Reporting:** Allure reports are deeply structured using `@allure.epic`, `feature`, and `story`. Complex cross-platform scenarios are prominently isolated in the **\"Hybrid Testing\"** epic for immediate visibility of API+UI integrations.\n\n",
    "## ⚙️ Setup & Installation\n\n",
    "1. Clone the repository:\n",
    f"{TICK}bash\n",
    "git clone [https://github.com/warmanofmars-star/QA3553_IlCarro_Tests.git](https://github.com/warmanofmars-star/QA3553_IlCarro_Tests.git)\n",
    f"{TICK}\n\n",
    "2. Create and activate a virtual environment.\n\n",
    "3. Install dependencies:\n",
    f"{TICK}bash\n",
    "pip install -r requirements.txt\n",
    "playwright install\n",
    f"{TICK}\n\n",
    "4. Create a `.env` file in the root directory and add your credentials:\n",
    f"{TICK}env\n",
    "USER_EMAIL=your_test_email@gmail.com\n",
    "USER_PASSWORD=your_secure_password\n",
    "HEADLESS_MODE=false\n",
    "ENABLE_CONSOLE_LOGS=true\n",
    f"{TICK}\n\n",
    "## 🏃‍♂️ How to Run Tests\n\n",
    "**Run all tests (Selenium UI, API, and Playwright) in parallel with 3 workers:**\n",
    f"{TICK}bash\n",
    "pytest tests/ -s -n 3 --clean-alluredir --alluredir=allure-results\n",
    f"{TICK}\n\n",
    "**Run modern Playwright tests (headed mode for debugging):**\n",
    f"{TICK}bash\n",
    "pytest tests/test_playwright_*.py -s --headed\n",
    f"{TICK}\n\n",
    "**Generate and view Allure Report locally:**\n",
    f"{TICK}bash\n",
    "allure serve allure-results\n",
    f"{TICK}\n\n",
    "## 📊 CI/CD Pipeline\n",
    "The project is fully integrated with **GitHub Actions**. Upon every manual dispatch, the pipeline:\n",
    "1. Sets up the Python environment and installs dependencies.\n",
    "2. Executes the full test suite in headless mode.\n",
    "3. Generates an Allure Report.\n",
    "4. Deploys the report to GitHub Pages.\n",
    "5. Sends a Telegram notification with a direct link to the test results.\n\n",
    "## 🏗 Project Structure\n",
    f"{TICK}text\n",
    "QA3553_IlCarro_Tests/\n",
    "├── .github/workflows/    # CI/CD pipeline configuration\n",
    "├── api/                  # API Client (Requests) for backend interactions\n",
    "├── data/                 # Test data generators (Faker)\n",
    "├── models/               # Data classes (Car, User)\n",
    "├── pages/                # Page Object Model classes (Selenium & Playwright)\n",
    "├── tests/                # Test suites grouped by context\n",
    "├── utils/                # Custom logger, WebDriver listener, API helpers\n",
    "├── logs/                 # Auto-rotating local log files\n",
    "├── conftest.py           # Pytest fixtures and WebDriver/Playwright setup\n",
    "└── requirements.txt      # Project dependencies\n",
    f"{TICK}\n\n",
    "---\n",
    "*Author: Maxim Vinogradov*\n"
]

with open("README.md", "w", encoding="utf-8") as f:
    f.writelines(lines)

print("✅ Файл README.md успешно перезаписан! Можно пушить.")