# make_readme.py

TICK = "`" * 3

lines = [
    "# 🚗 IlCarro Hybrid Test Automation Framework\n\n",
    "[![UI Tests in Docker](https://github.com/warmanofmars-star/QA3553_IlCarro_Tests/actions/workflows/tests.yml/badge.svg)](https://github.com/warmanofmars-star/QA3553_IlCarro_Tests/actions)\n",
    "📊 **Live Allure Report:** [View Dashboard](https://warmanofmars-star.github.io/QA3553_IlCarro_Tests/)\n\n",
    "Robust, production-ready hybrid test automation framework for the \"IlCarro\" (Car Rental) web application, featuring a fully containerized **Infrastructure as Code (IaC)** approach.\n\n",
    "This project demonstrates a senior-level approach to QA automation, combining classic UI testing, API integration, remote browser execution via Selenoid, advanced network mocking, and modern container orchestration.\n\n",
    "## 🛠️ Tech Stack\n",
    "* **Language:** Python 3.12\n",
    "* **UI Frameworks:** Selenium WebDriver, Playwright (Sync API)\n",
    "* **API Testing:** Requests\n",
    "* **Containerization & Orchestration:** Docker, Docker Compose, Selenoid (with video-recorder)\n",
    "* **Test Runner:** Pytest (with `pytest-xdist` for parallel execution)\n",
    "* **Data Generation:** Faker & UUID\n",
    "* **Reporting:** Allure Report (with embedded test session videos)\n",
    "* **CI/CD:** GitHub Actions (Fully containerized pipeline)\n",
    "* **Notifications:** Telegram Bot API\n\n",
    "## 🚀 Key Architectural Features\n\n",
    "* **Dockerized Infrastructure (IaC):** The entire test environment (framework, Selenoid hub, Chrome instances, video recording) is orchestrated via Docker Compose, guaranteeing absolute consistency across local machines and CI/CD.\n",
    "* **Strict Data Isolation (Sandbox Users):** Employs a robust `temp_user` fixture that dynamically registers a unique user via API before each test. This eliminates race conditions during aggressive parallel execution (`pytest-xdist`) and leaves the database unpolluted.\n",
    "* **Universal Video Attachment:** Every Selenium test is recorded via FFmpeg/Selenoid, while Playwright tests utilize the native recording engine. All resulting .mp4 files are automatically attached to the Allure report upon teardown.\n",
    "* **Hybrid Testing Approach:** Tests use API calls to set up preconditions (e.g., creating a car or user) and teardown data, drastically reducing UI test execution time.\n",
    "* **Network Interception & Mocking:** Utilizes Playwright's `page.route()` to intercept backend requests (e.g., fetching city lists) and inject mock responses, allowing strict isolation of frontend UI rendering logic from backend stability.\n",
    "* **Dual Framework Support:** Implemented primarily using **Selenium (Page Object Model)** with an integrated **Playwright** module to demonstrate modern tool capabilities.\n",
    "* **Security & Log Masking:** Sensitive data (passwords, tokens) are strictly masked (********) in all console outputs, test logs, and Allure reports.\n",
    "* **Context-Aware Custom Logging:** Features a proprietary logging utility, cleanly injected into test suites as a global Pytest fixture, that dynamically adapts to the execution environment, preventing OS-level file locks during parallel runs.\n",
    "* **API Connection Pooling:** Utilizes `requests.Session()` for backend interactions, reusing TCP connections and automatically managing Bearer tokens.\n\n",
    "## ⚙️ Setup & Installation\n\n",
    "1. Clone the repository:\n",
    f"{TICK}bash\n",
    "git clone https://github.com/warmanofmars-star/QA3553_IlCarro_Tests.git\n",
    f"{TICK}\n\n",
    "2. Create and activate a virtual environment.\n\n",
    "3. Install dependencies:\n",
    f"{TICK}bash\n",
    "pip install -r requirements.txt\n",
    "playwright install chromium\n",
    f"{TICK}\n\n",
    "4. Create a `.env` file in the root directory and add your credentials:\n",
    f"{TICK}env\n",
    "USER_EMAIL=your_test_email@gmail.com\n",
    "USER_PASSWORD=your_secure_password\n",
    "HEADLESS_MODE=false\n",
    "USE_SELENOID=false\n",
    "ENABLE_CONSOLE_LOGS=true\n",
    f"{TICK}\n\n",
    "## 🏃‍♂️ How to Run Tests\n\n",
    "**Run tests in the isolated Docker container (Recommended):**\n",
    f"{TICK}bash\n",
    "docker compose up --build --exit-code-from qa-framework\n",
    f"{TICK}\n\n",
    "**Run locally via Pytest (parallel execution):**\n",
    f"{TICK}bash\n",
    "pytest tests/ -n 3 --video=on --clean-alluredir --alluredir=allure-results\n",
    f"{TICK}\n\n",
    "**Run modern Playwright tests (headed mode for debugging):**\n",
    f"{TICK}bash\n",
    "pytest tests/test_playwright_*.py -s --headed\n",
    f"{TICK}\n\n",
    "**Generate and view Allure Report locally:**\n",
    f"{TICK}bash\n",
    "allure serve allure-results\n",
    f"{TICK}\n\n",
    "## 📊 CI/CD Pipeline\n",
    "The project features an advanced **GitHub Actions** pipeline:\n",
    "* Automatically triggers on manual dispatch (`workflow_dispatch`).\n",
    "* Spins up a clean Linux runner, builds the Docker Compose stack, and executes all tests in parallel.\n",
    "* Securely injects credentials via **GitHub Secrets**.\n",
    "* Generates and deploys the Allure report to **GitHub Pages**.\n",
    "* Sends automated execution status notifications with a direct link to Telegram.\n\n",
    "## 🏗 Project Structure\n",
    f"{TICK}text\n",
    "QA3553_IlCarro_Tests/\n",
    "├── .github/workflows/    # CI/CD pipeline configuration (tests.yml)\n",
    "├── api/                  # API Client (Requests) for backend interactions\n",
    "├── data/                 # Test data generators (Faker, UUID)\n",
    "├── models/               # Data classes (Car, User)\n",
    "├── pages/                # Page Object Model classes (Selenium & Playwright)\n",
    "├── selenoid/             # Selenoid configuration (browsers.json)\n",
    "├── tests/                # Test suites grouped by context\n",
    "├── utils/                # Custom logger, WebDriver listener, API helpers\n",
    "├── logs/                 # Auto-rotating local log files\n",
    "├── conftest.py           # Pytest fixtures, Selenoid connection, video attachment hooks\n",
    "├── Dockerfile            # Container definition for the test framework\n",
    "├── docker-compose.yml    # Infrastructure orchestration (Selenoid + Framework + Network + Volumes)\n",
    "└── requirements.txt      # Project dependencies\n",
    f"{TICK}\n\n",
    "---\n",
    "*Author: Maksim Vinogradov*\n"
]

with open("README.md", "w", encoding="utf-8") as f:
    f.writelines(lines)

print("✅ Файл README.md успешно перезаписан! Можно пушить.")