[pytest]
markers =
    smoke: Быстрые тесты критического функционала (Login, Registration, Add Car)
    regression: Глубокие проверки, негативные сценарии и валидация форм
    api: Тесты бэкенда (без поднятия браузера)
    hybrid: E2E тесты на стыке UI и API