name: IlCarro UI Tests

on:
  workflow_dispatch:

# РАЗРЕШАЕМ РОБОТУ ПИСАТЬ В РЕПОЗИТОРИЙ (Для создания ветки gh-pages)
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  test:
    runs-on: ubuntu-22.04 # Фиксируем стабильную версию Linux для предсказуемости

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # 👇 1. Динамически создаем .env файл для Docker
      - name: Setup environment variables for Docker
        run: |
          echo "USER_EMAIL=${{ secrets.USER_EMAIL }}" >> .env
          echo "USER_PASSWORD=${{ secrets.USER_PASSWORD }}" >> .env

      # 👇 2. Предварительно скачиваем тяжелые образы, чтобы тесты не падали по таймауту
      - name: Pull Selenoid Chrome image
        run: docker pull selenoid/chrome:128.0

      - name: Pull Selenoid Video Recorder image
        run: docker pull selenoid/video-recorder:latest-release

      # 👇 3. Запускаем всю нашу инфраструктуру одной командой
      - name: Run Tests in Docker Compose
        run: docker compose up --build --exit-code-from qa-framework
        continue-on-error: true

      # --- БЕЗОТКАЗНАЯ ГЕНЕРАЦИЯ ОТЧЕТА ЧЕРЕЗ NPM (БЕЗ DOCKER) ---
      - name: Generate Allure Report
        if: always()
        run: |
          npm install -g allure-commandline --save-dev
          allure generate allure-results -o allure-report --clean

      # --- ПУБЛИКАЦИЯ СГЕНЕРИРОВАННОЙ ПАПКИ В GH-PAGES ---
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-report

      # --- ОТПРАВКА УВЕДОМЛЕНИЯ В ТЕЛЕГРАМ ---
      - name: Send Telegram Notification
        uses: appleboy/telegram-action@master
        if: always()
        with:
            to: ${{ secrets.TELEGRAM_TO }}
            token: ${{ secrets.TELEGRAM_TOKEN }}
            message: |
              🤖 Автотесты IlCarro завершены (Docker Environment)!
              📊 Посмотреть Allure-отчет можно по ссылке:
              👉 https://warmanofmars-star.github.io/QA3553_IlCarro_Tests/